language: go

go:
  - 1.13.1

env:
  global:
    - TIO_VERSION=v0.1.0
    - TIO_BUILD_NAME=tioserverless/build
    - TIO_CONTROL_NAME=tioserverless/control
    - TIO_BUILD_AGENT_HOST_NAME=tioserverless/build-agent-host
    - TIO_CONSUL_AGENT=tioserverless/consul-agent
    - TIO_CONSUL_WATCH=tioserverless/consul-watch
    - TIO_DEPLOY_AGENT=tioserverless/deploy-agent
    - TIO_BUILD_AGENT_K8S_NAME=tioserverless/build-agent-k8s

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin

install:
  - go test -v ./...
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-build build/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-control control/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-build-agent-host build-agent/host/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-build-agent-k8s build-agent/k8s/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/consul-agent consul/sidecar/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-deploy deploy-agent/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-consul-watch consul/watch/*.go
  - go build -mod=vendor -ldflags "-X tio/client/cmd._VERSION_=$TIO_VERSION -X tio/client/cmd._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-cli client/*.go


after_script:
  - docker build -t ${TIO_BUILD_NAME}:http-${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.build-http Dockerfile
  - docker push ${TIO_BUILD_NAME}:http-${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_BUILD_NAME}:grpc-${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.build-grpc Dockerfile
  - docker push ${TIO_BUILD_NAME}:grpc-${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_CONTROL_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.control Dockerfile
  - docker push ${TIO_CONTROL_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_BUILD_AGENT_HOST_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.build-agent-host Dockerfile
  - docker push  ${TIO_BUILD_AGENT_HOST_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_BUILD_AGENT_K8S_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.build-agent-k8s Dockerfile
  - docker push  ${TIO_BUILD_AGENT_K8S_NAME}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_CONSUL_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.consul-sidecar Dockerfile
  - docker push ${TIO_CONSUL_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_DEPLOY_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.deploy-agent Dockerfile
  - docker push ${TIO_DEPLOY_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_CONSUL_WATCH}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.consul-watch Dockerfile
  - docker push ${TIO_CONSUL_WATCH}:${TIO_VERSION}-${TRAVIS_BRANCH}